app/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns

from .views import ContactFormView
from .views import LandingPageView
from .views import DashboardView
from .views import JobOfferApplyView
from .views import JobOfferDetail
from .views import JobsList
from .views import ProfessionalDetail
from .views import user_logout
from .views import CompanyDetail
from .views import CompanyList
from .views import SignupView
from account.forms import UserPasswordResetForm

admin.site.site_title = 'QueryJane'
admin.site.site_header = 'QueryJane - Administrador'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    url(
        r'^$',
        LandingPageView.as_view(),
        name='landing_page',
    ),

    url(
        r'^signup/$',
        SignupView.as_view(),
        name='signup',
    ),

    url(
        r'^dashbaord/$',
        DashboardView.as_view(),
        name='dashboard',
    ),

    url(
        r'^companies/$',
        CompanyList.as_view(),
        name='companies_list',
    ),

    url(
        r'^jobs/$',
        JobsList.as_view(),
        name='jobs_list',
    ),

    url(
        r'^jobs/(?P<slug>[-\w]+)/$',
        JobOfferDetail.as_view(),
        name='job_offer_detail',
    ),

    url(
        r'^jobs/(?P<slug>[-\w]+)/apply/$',
        JobOfferApplyView.as_view(),
        name='job_offer_apply',
    ),

    url(
        r'^contact_form/$',
        ContactFormView.as_view(),
        name='contact_form',
    ),

    url(
        r'^contact_form_success/$',
        TemplateView.as_view(template_name='corporative/contact_form_success.html'),
        name='contact_form_success',
    ),

    url(
        r'^password/recovery/$',
        auth_views.PasswordResetView.as_view(
            template_name='account/auth/password_reset_form.html',
            form_class=UserPasswordResetForm,
            html_email_template_name='account/auth/password_reset_email.html',
        ),
        name='password_reset',
    ),

    url(
        r'^password/recovery/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/auth/password_reset_done.html',
        ),
        name='password_reset_done',
    ),

    url(
        r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('auth_login'),
            post_reset_login=True,
            template_name='account/auth/password_reset_confirm.html',
            post_reset_login_backend=(
                'django.contrib.auth.backends.AllowAllUsersModelBackend'
            ),
        ),
        name='password_reset_confirm',
    ),

    url(
        r'^login/$',
        auth_views.login,
        {
            'template_name': 'account/auth/login.html',
            'redirect_authenticated_user': True,
        },
        name='auth_login',
    ),

    url(
        r'^logout/$',
        user_logout,
        name='user_logout',
    ),

    url(
        r'^corporative/',
        include(
            'corporative.urls',
            namespace='corporative',
        )
    ),
    url(r'^account/', include('account.urls', namespace='account')),

    url(
        r'^entrepreneur/',
        include(
            'entrepreneur.urls',
            namespace='entrepreneur',
        )
    ),
    url(r'^place/', include('place.urls', namespace='place')),

    url(
        r'^(?P<slug>[-\w]+)/$',
        CompanyDetail.as_view(),
        name='venture_detail',
    ),
    url(
        r'^profile/(?P<slug>[-\w]+)/$',
        ProfessionalDetail.as_view(),
        name='professional_detail',
    ),
)

corporative/urls.py
from django.conf.urls import url

from .views import ActivateJobOfferView
from .views import ActivateCompanyView
from .views import AdminDashboardView
from .views import HideJobOfferView
from .views import HideCompanyView
from .views import LegalItemView
from .views import LegalItemFormView
from .views import TwitterShareJobView
from .views import TwitterShareCompanyView
from .views import LegalItemAgreeView
from .views import CityBulkFormView

urlpatterns = [
    url(
        r'^admin_dashboard/$',
        AdminDashboardView.as_view(),
        name='admin_dashboard',
    ),

    url(
        r'^ax-twitter-share/(?P<slug>[-\w]+)/venture/$',
        TwitterShareCompanyView.as_view(),
        name='ax_twitter_share_company',
    ),

    url(
        r'^ax-twitter-share/(?P<slug>[-\w]+)/job/$',
        TwitterShareJobView.as_view(),
        name='ax_twitter_share_job',
    ),

    url(
        r'^ax-hide/(?P<slug>[-\w]+)/venture/$',
        HideCompanyView.as_view(),
        name='ax_hide_company',
    ),

    url(
        r'^ax-activate/(?P<slug>[-\w]+)/venture/$',
        ActivateCompanyView.as_view(),
        name='ax_activate_company',
    ),

    url(
        r'^ax-hide/(?P<slug>[-\w]+)/job_offer/$',
        HideJobOfferView.as_view(),
        name='ax_hide_job_offer',
    ),

    url(
        r'^ax-activate/(?P<slug>[-\w]+)/job_offer/$',
        ActivateJobOfferView.as_view(),
        name='ax_activate_job_offer',
    ),

    url(
        r'^legal_item_agree/(?P<slug>[-\w]+)/$',
        LegalItemAgreeView.as_view(),
        name='legal_item_agree',
    ),

    url(
        r'^city-bulk-form/$',
        CityBulkFormView.as_view(),
        name='city_bulk_form',
    ),

    url(
        r'^(?P<slug>[-\w]+)/update/$',
        LegalItemFormView.as_view(),
        name='legal_item_form',
    ),
    url(
        r'^(?P<slug>[-\w]+)/',
        LegalItemView.as_view(),
        name='legal_item',
    ),
]

corporative/models.py
from django.db import models
from django.utils.translation import ugettext as _


class LegalItem(models.Model):
    """
    Legal item model. Privacy policy, user agreement and
    cookies policy are predefined objects of this model.
    """
    sp_title = models.CharField(
        max_length=50,
        verbose_name=_('Spanish title'),
    )

    en_title = models.CharField(
        max_length=50,
        verbose_name=_('English title'),
    )

    sp_description = models.TextField(
        blank=True,
        null=True,
        verbose_name=_('Spanish description'),
    )

    en_description = models.TextField(
        blank=True,
        null=True,
        verbose_name=_('English description'),
    )

    slug = models.SlugField()

    updated_at = models.DateTimeField()

    def __str__(self):
        return '{0}'.format(self.en_title)

    class Meta:
        verbose_name = _('Legal item')
        verbose_name_plural = _('Legal items')
        ordering = ('-updated_at',)

corporative/views.py
import xlrd

from django.conf import settings

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic import UpdateView
from django.views.generic import View
from django.views.generic import FormView
from django.template.loader import render_to_string

from .models import LegalItem
from .permissions import AdminPermissions
from account.data import UPDATED_PRIVACY_POLICY
from account.data import UPDATED_TERMS
from account.models import User
from account.models import UserNotification
from app.tasks import send_email
from app.mixins import CustomUserMixin
from corporative.forms import LegalItemForm
from corporative.tasks import share_company_on_twitter
from corporative.tasks import share_job_on_twitter
from corporative.forms import FormBulkForm
from entrepreneur.data import JOB_STATUS_ACTIVE
from entrepreneur.data import JOB_STATUS_HIDDEN
from entrepreneur.data import VENTURE_STATUS_ACTIVE
from entrepreneur.data import VENTURE_STATUS_HIDDEN
from entrepreneur.models import JobOffer
from entrepreneur.models import Venture
from place.models import State
from place.models import City
from place.models import Country


class LegalItemView(DetailView):
    """
    User agreement, privacy policy and cookies policy
    are consireded legal items. This view showa the
    legal items detail. If the authenticated user is
    platform administrator, the edit legal item form
    will be available.
    """
    model = Venture
    template_name = 'corporative/legal_item.html'

    def get_object(self):
        # Get current legal item by slug in the url.
        return get_object_or_404(
            LegalItem,
            slug=self.kwargs.get('slug'),
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Check if user is authenticated and if user is admin.
        is_admin = AdminPermissions.can_manage_admin_views(
            user=self.request.user,
        )
        # If can edit, the edit legal item form will be available.
        context['can_edit'] = is_admin

        # Instance current legal item in the edit form.
        if is_admin:
            context['legal_item_form'] = LegalItemForm(
                instance=self.get_object(),
            )

        return context


class LegalItemFormView(CustomUserMixin, UpdateView):
    """
    Form view to update legal items. Only platform administrators
    can submit this form. Users can select if the change is very important
    and if it requires to notify all registered users about it.
    """
    form_class = LegalItemForm
    template_name = 'corporative/legal_item.html'

    def get_success_url(self):
        return reverse(
            'corporative:legal_item',
            kwargs={'slug': self.kwargs.get('slug')}
        )

    def get_object(self):
        # Get legal item by slug.
        return get_object_or_404(
            LegalItem,
            slug=self.kwargs.get('slug'),
        )

    def test_func(self):
        return AdminPermissions.can_manage_admin_views(
            user=self.request.user,
        )

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('landing_page')

        return super().get(request, *args, **kwargs)

    @transaction.atomic
    def form_valid(self, form):
        # Save legal item.
        legal_item = form.save()

        # Notify users field. If the value is True, all
        # platform users will be notified about the change.
        notify_users = form.cleaned_data['notify_users']

        if notify_users:
            # Update the date in which the legal item was updated.
            legal_item.updated_at = timezone.now()

            # Notify all users about the new legal item update.
            for user in User.objects.all():
                if legal_item.slug == 'privacy-policy':
                    user.accepted_privacy_policy = False
                    notification_type = UPDATED_PRIVACY_POLICY
                    description = 'Our privacy policy has been updated.'

                elif legal_item.slug == 'user-agreement':
                    user.accepted_terms = False
                    notification_type = UPDATED_TERMS
                    description = 'Our user agreement has been updated.'

                user.save()

                # Create notification about legal item update for all
                # registered users.
                UserNotification.objects.create(
                    notification_type=notification_type,
                    noty_to=user,
                    description=description,
                )

                # Create email to notify all users about legal item update.
                body = render_to_string(
                    'corporative/emails/legal_item_update.html', {
                        'title': description,
                        'user_to': user,
                        'notification_type': notification_type,
                        'base_url': settings.BASE_URL,
                    },
                )

                # Send email.
                send_email(
                    subject=description,
                    body=body,
                    mail_to=[user.email],
                )

        legal_item.save()

        messages.success(
            self.request,
            _('legal item has been successfully updated.')
        )

        return super().form_valid(form)


class LegalItemAgreeView(LoginRequiredMixin, View):
    """
    View to accept new legal items. Users are notified
    when a legal item is updated and teh must accept the
    new terms.
    """
    @transaction.atomic
    def get(self, request, *args, **kwargs):
        user = request.user
        item = self.kwargs.get('slug')

        # Set to True if users accept legal item updates.
        if item == 'user-agreement':
            user.accepted_terms = True
            user.accepted_terms_date = timezone.now()

            # Set notification as seen.
            UserNotification.objects.filter(
                noty_to=user,
                notification_type=UPDATED_TERMS,
            ).update(was_seen=True)

        if item == 'privacy-policy':
            user.accepted_privacy_policy = True
            user.accepted_privacy_policy_date = timezone.now()

            # Set notification as seen.
            UserNotification.objects.filter(
                noty_to=user,
                notification_type=UPDATED_PRIVACY_POLICY,
            ).update(was_seen=True)
        user.save()

        messages.success(
            self.request,
            _(
                'Thank you. We will notify you whenever there is a '
                'change in our privacy policy or in our user agreement.'
            )
        )

        return redirect('landing_page')


class AdminDashboardView(CustomUserMixin, TemplateView):
    """
    Platform administrators dashboard. Exclusive actions for
    administrators are found here as hide jobs or ventures
    or share companies and ventures in the official Qjane
    social networks.
    """
    template_name = 'corporative/admin_dashboard.html'

    def test_func(self):
        return AdminPermissions.can_manage_admin_views(
            user=self.request.user,
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # List of companies that have not been shared in the
        # Qjane official social networks.
        context['unshared_companies_list'] = Venture.objects.filter(
            status=VENTURE_STATUS_ACTIVE,
            shared_on_twitter=False
        )

        # List of jobs that have not been shared in the Qjane
        # official social networks.
        context['unshared_jobs_list'] = JobOffer.objects.filter(
            status=JOB_STATUS_ACTIVE,
            shared_on_twitter=False
        )

        # List of hidden companies.
        context['hidden_companies'] = Venture.objects.filter(
            status=VENTURE_STATUS_HIDDEN,
        )

        # List of hidden job offers.
        context['hidden_job_offer'] = JobOffer.objects.filter(
            status=JOB_STATUS_HIDDEN,
        )

        return context


class TwitterShareCompanyView(CustomUserMixin, View):
    """
    Ajax View to share a company detail page in the offical
    Qjane Twitter account. Only administrators can share
    companies in social networks.
    """
    def test_func(self):
        return AdminPermissions.can_share_company_twitter(
            user=self.request.user,
            company=self.get_object(),
        )

    def get_object(self):
        return get_object_or_404(Venture, slug=self.kwargs.get('slug'))

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        share_company_on_twitter(self.get_object())

        return HttpResponse('success')


class TwitterShareJobView(CustomUserMixin, View):
    """
    Ajax View to share a job offer detail page in the offical
    Qjane Twitter account. Only administrators can share
    job offers in social networks.
    """
    def test_func(self):
        return AdminPermissions.can_share_job_twitter(
            user=self.request.user,
            job=self.get_object(),
        )

    def get_object(self):
        return get_object_or_404(JobOffer, slug=self.kwargs.get('slug'))

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        share_job_on_twitter(self.get_object())

        return HttpResponse('success')

corporative/templates/corporative/admin_dashboard.html
{% extends "layout/base.html" %}
{% load static i18n %}

{% block title %}{% trans 'Admin dashboard' %}{% endblock %}

{% block css %}
<link href="{% static 'dist/css/layout/layout.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section class="AdminDashboard">

    <div class="container py-4">

        <a href="{% url 'corporative:city_bulk_form' %}">Load cities by country form.</a>

        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="companies-admin-tab" data-toggle="tab" href="#companiesAdmin" role="tab" aria-controls="companies-admin" aria-selected="true">
                    {% trans 'Companies' %}
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" id="social-networks-admin-tab" data-toggle="tab" href="#socialnetworksAdmin" role="tab" aria-controls="social-networks-admin" aria-selected="false">
                    {% trans 'Social Networks' %}
                </a>
            </li>
        </ul>

        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active p-3" id="companiesAdmin" role="tabpanel" aria-labelledby="companies-admin-tab">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <div class="card rounded-0 border-0">
                            <div class="card-header bg-qj-purple rounded-0">
                                <h3 class="h5 m-0 text-white">{% trans 'Hidden companies' %}</h3>
                            </div>
                            <div class="card-body border border-muted border-top-0">
                                {% if hidden_companies %}
                                <table class="table table-striped jobs-table mb-0">
                                <tbody>
                                {% for company in hidden_companies %}
                                    {% include 'account/dashboard_company_line.html' %}
                                {% endfor %}
                                </tbody>
                                </table>
                                {% else %}
                                <p class="h4 mb-0">{% trans 'There are not hidden companies.' %}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-sm-6">
                        <div class="card rounded-0 border-0">
                            <div class="card-header bg-qj-purple rounded-0">
                                <h3 class="h5 m-0 text-white">{% trans 'Hidden Job offers' %}</h3>
                            </div>
                            <div class="card-body border border-muted border-top-0">
                                {% if hidden_job_offer %}
                                <table class="table table-striped jobs-table mb-0">
                                <tbody>
                                {% for job_offer in hidden_job_offer %}
                                    {% include 'account/dashboard_job_offer_line.html' %}
                                {% endfor %}
                                </tbody>
                                </table>
                                {% else %}
                                <p class="h4 mb-0">{% trans 'There are not hidden job offers.' %}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tab-pane fade p-3" id="socialnetworksAdmin" role="tabpanel" aria-labelledby="social-networks-admin-tab">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <div class="card rounded-0 border-0">
                            <div class="card-header bg-qj-purple rounded-0">
                                <h3 class="h5 m-0 text-white">{% trans 'Companies to share' %}</h3>
                            </div>
                            <div class="card-body border border-muted border-top-0">
                                {% if unshared_companies_list %}
                                <table class="table table-striped jobs-table mb-0">
                                <tbody>
                                {% for company in unshared_companies_list %}
                                    {% include 'account/dashboard_company_line.html' %}
                                {% endfor %}
                                </tbody>
                                </table>
                                {% else %}
                                <p class="h4 mb-0">{% trans 'There are not unshared companies.' %}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-sm-6">
                        <div class="card rounded-0 border-0">
                            <div class="card-header bg-qj-purple rounded-0">
                                <h3 class="h5 m-0 text-white">{% trans 'Job offers to share' %}</h3>
                            </div>
                            <div class="card-body border border-muted border-top-0">
                                {% if unshared_jobs_list %}
                                <table class="table table-striped jobs-table mb-0">
                                <tbody>
                                {% for job_offer in unshared_jobs_list %}
                                    {% include 'account/dashboard_job_offer_line.html' %}
                                {% endfor %}
                                </tbody>
                                </table>
                                {% else %}
                                <p class="h5 mb-0">{% trans 'There are not unshared job offers' %}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
<script src="{% static 'dist/js/corporative/staff_company_actions.min.js' %}"></script>
{% endblock %}

corporative/templates/corporative/city_bulk_form.html
{% extends "layout/base.html" %}
{% load static i18n widget_tweaks %}

{% block title %}{% trans 'Create all cities database for a specific country.' %}{% endblock %}

{% block css %}
<link href="{% static 'dist/css/layout/layout.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section class="AdminDashboard">
    <div class="container py-4">
      <p>Upload cities and states for an specific country code.</p>

      <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% if form.non_field_errors %}
        <div class="form-group">{{ form.non_field_errors }}</div>
      {% endif %}

        <div class="row">
          <div class="form-group col-md-6">
            <p>{{ form.country_code.label_tag }}</p>
            {% render_field form.country_code class+="form-control" %}
            {{ form.country_code.errors }}
          </div>

          <div class="form-group col-md-6">
            <p>{{ form.excel_file.label_tag }}</p>
            {% render_field form.excel_file class+="form-control" %}
            {{ form.excel_file.errors }}
            <p class="font-weight-light">{{ form.excel_file.help_text }}</p>
          </div>
        </div>

        <button type="submit" class="btn btn-outline-info">{% trans "Cargar" %}</button>
      </form>
    </div>
</section>
{% endblock %}

{% block js %}
{% endblock %}

corporative/templates/corporative/contact_form.html
{% extends "layout/base.html" %}
{% load widget_tweaks static i18n %}

{% block title %}{% trans 'Contact Us' %}{% endblock %}

{% block css %}
<link href="{% static 'dist/css/layout/layout.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
  <div class="container py-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="text-center">
          <h1>{% trans 'Contact Us!' %}</h1>

          <p>{% trans 'Do you think we can help you with advice in the cannabis industry?' %}</p>
          <p>{% trans 'Do you have questions about the use of the platform?' %}</p>
          <p>---</p>
        </div>

        <p>{% trans 'Feel free to contact us, we will be happy to talk about how we can help boost the cannabis industry and to listen your doubts and suggestions.' %}</p>

        <form method="post" id="idContactForm">
            {% csrf_token %}
            <div class="form-group">
                {{ form.subject.label_tag }}
                {% render_field form.subject class+="form-control" %}
                {{ form.subject.errors }}
            </div>

            <div class="form-group name">
                {{ form.name.label_tag }}
                {% render_field form.name class+="form-control" %}
                {{ form.name.errors }}
            </div>

            <div class="form-group email {% if user.is_authenticated %}d-none{% endif %}">
                {{ form.email.label_tag }}
                {% render_field form.email class+="form-control" %}
                {{ form.email.errors }}
            </div>

            <div class="form-group phone">
                {{ form.phone.label_tag }}
                {% render_field form.phone class+="form-control" %}
                {{ form.phone.errors }}
            </div>

            <div class="form-group message">
                {{ form.message.label_tag }}
                {% render_field form.message class+="form-control" %}
                {{ form.message.errors }}
            </div>
            <button type="submit" class="btn btn-primary">{% trans 'send' %}</button>
        </form>
        <br>
        <br>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block js %}
<script src="{% static 'dist/js/corporative/contact_form.min.js' %}"></script>
{% endblock %}

corporative/templates/corporative/contact_form_success.html
{% extends "layout/base.html" %}
{% load widget_tweaks static i18n %}

{% block title %}{% trans 'Thank you for contacting us' %}{% endblock %}

{% block content %}
<div class="container">
  <div class="QJContactFormSuccess">
    <div class="row">
      <div class="col-sm-8 offset-sm-2 col-lg-6 offset-lg-3 text-center">
        <h1 class="h1">{% trans 'Thank you for contacting us!!!' %}</h1>

        <p class="h5">---</p>

        <p class="h4">{% trans 'We have received your message and we will get in touch with you soon.' %}</p>

        <p class="h5">---</p>


        <a href="{% url 'landing_page' %}" class="btn btn-primary">{% trans 'Go to home page' %}</a>

        <a href="{% url 'companies_list' %}" class="btn btn-ghost-purple">{% trans 'Take a look to the companies list' %}</a>

        <a href="{% url 'jobs_list' %}" class="btn btn-ghost-purple">{% trans 'Take a look to the job offers list' %}</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

corporative/templates/corporative/legal_item.html
{% extends "layout/base.html" %}

{% load static i18n widget_tweaks legal_item_tags notifications %}

{% block title %}{{ object.en_title }}{% endblock %}

{% block css %}
<link href="{% static 'dist/css/layout/layout.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container py-4">
  <h1>{{ object.en_title }}</h1>

  {% if can_edit %}
  <div class="text-right">
    <button type="submit" class="btn btn-primary EditLegalItemToggle">{% trans 'Edit' %}</button>
  </div>

  <form class="mb-4" id="idEditLegalItemForm" method="post" action="{% url 'corporative:legal_item_form' object.slug %}" style="display: none;">
      {% csrf_token %}

    <div class="form-group">
      <label>
        {{ legal_item_form.en_description.label_tag }}
        <span class="text-danger">*</span>
      </label>

      <div id="rich_editor_en_description">{{ object.en_description|safe }}</div>
      <p>{{ form.description_en.errors }}</p>
    </div>

    <div class="form-group">
      <label>
        {{ legal_item_form.sp_description.label_tag }}
        <span class="text-danger">*</span>
      </label>

      <div id="rich_editor_sp_description">{{ object.sp_description|safe }}</div>
      <p>{{ form.description_es.errors }}</p>
    </div>

    {% if object.slug != 'cookies-policy' %}
    <div class="form-group">
      <label>{{ legal_item_form.notify_users.label_tag }}</label>

      {% render_field legal_item_form.notify_users %}
      <p>{{ legal_item_form.notify_users.help_text }}<p>
    </div>
    {% endif %}

    <div class="form-group" style="display: none;">
    {% render_field legal_item_form.sp_description %}
    {% render_field legal_item_form.en_description %}
    </div>

    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
  </form>
  {% endif %}

  {% get_legal_item_description object.slug as item_description %}
  <div>{{ item_description|safe }}</div>

  <div class="text-right">
  {% trans 'last update:' %} {{ object.updated_at }}
  </div>

{% if user.is_authenticated and not user.accepted_terms and object.slug == 'user-agreement' %}
  <a href="{% url 'corporative:legal_item_agree' object.slug %}" class="btn btn-primary">
    {% trans 'I agree' %}
  </a>
{% endif %}

{% if user.is_authenticated and not user.accepted_privacy_policy and object.slug == 'privacy-policy' %}
  <a href="{% url 'corporative:legal_item_agree' object.slug %}" class="btn btn-primary">
    {% trans 'I agree' %}
  </a>
{% endif %}
</div>
{% endblock %}

{% block js %}
<script src="{% static 'dist/js/corporative/legal_item.min.js' %}"></script>
{% endblock %}