account/urls.py
from django.conf.urls import url

from account.views.address_book import AddCompanyToAddressBookView
from account.views.address_book import AddressBookView
from account.views.address_book import AddUserToAddressBookView
from account.views.address_book import RemoveCompanyToAddressBookView
from account.views.address_book import RemoveUserFromAddressBookView
from account.views.company_score import CompanyScoreEditView
from account.views.company_score import CompanyScoreFormView
from account.views.company_score import CompanyScoreRemoveView
from account.views.messages import InboxView
from account.views.messages import LoadConversationView
from account.views.messages import UserMessageFormView
from account.views.notifications import AdminNotificationAcceptView
from account.views.notifications import AdminNotificationRejectView
from account.views.notifications import AdminNotificationResendView
from account.views.notifications import LoadNotificationModal
from account.views.notifications import NotificationsView
from account.views.profile import DeactivateAccountView
from account.views.profile import DeleteAccountMessageView
from account.views.profile import DeleteAccountView
from account.views.profile import EmailNotificationsUpdateView
from account.views.profile import NewUserLandingView
from account.views.profile import ProfessionalProfileCategoryView
from account.views.profile import ProfileSearch
from account.views.profile import UpdateProfileAvatarForm
from account.views.profile import UpdateProfileDescriptionForm
from account.views.profile import UpdateProfileFormView
from account.views.profile import ActivateAccountView

urlpatterns = [
    # API Userprofile
    url(
        r'^profile-search/$',
        ProfileSearch.as_view(),
        name='profile-search',
    ),

    url(
        r'^landing/$',
        NewUserLandingView.as_view(),
        name='signup_landing',
    ),

    url(
        r'^update/$',
        UpdateProfileFormView.as_view(),
        name='profile_update',
    ),

    url(
        r'^ax-deactivate-account/$',
        DeactivateAccountView.as_view(),
        name='deactivate_account',
    ),

    url(
        r'^ax-activate-account/$',
        ActivateAccountView.as_view(),
        name='activate_account',
    ),

    url(
        r'^ax-delete-account-message/$',
        DeleteAccountMessageView.as_view(),
        name='delete_account_message',
    ),

    url(
        r'^delete/$',
        DeleteAccountView.as_view(),
        name='account_delete',
    ),

    url(
        r'^address-book/$',
        AddressBookView.as_view(),
        name='address_book',
    ),

    url(
        r'^ax_update_professional_profile_category/$',
        ProfessionalProfileCategoryView.as_view(),
        name='ax_update_professional_profile_category',
    ),

    url(
        r'^ax_account/update_description/$',
        UpdateProfileDescriptionForm.as_view(),
        name='update_profile_description_form',
    ),

    url(
        r'^ax-post-notification-load/(?P<pk>\d+)/$',
        LoadNotificationModal.as_view(),
        name='ajax_post_notification_load',
    ),

    url(
        r'^admin_notification_accept/(?P<pk>\d+)/$',
        AdminNotificationAcceptView.as_view(),
        name='admin_notification_accept',
    ),

    url(
        r'^admin_notification_reject/(?P<pk>\d+)/$',
        AdminNotificationRejectView.as_view(),
        name='admin_notification_reject',
    ),

    url(
        r'^ax_admin_notification_resend/(?P<pk>\d+)/$',
        AdminNotificationResendView.as_view(),
        name='admin_notification_resend',
    ),

    url(
        r'^ax_send_user_mesasge/$',
        UserMessageFormView.as_view(),
        name='send_user_mesasge',
    ),

    url(
        r'^ax_company_score_form/(?P<pk>\d+)/$',
        CompanyScoreFormView.as_view(),
        name='company_score_form',
    ),

    url(
        r'^ax_company_score_remove/(?P<pk>\d+)/$',
        CompanyScoreRemoveView.as_view(),
        name='company_score_remove',
    ),

    url(
        r'^ax_company_score_edit/(?P<pk>\d+)/$',
        CompanyScoreEditView.as_view(),
        name='company_score_edit',
    ),

    url(
        r'^ax-post-conversation-load/(?P<pk>\d+)/$',
        LoadConversationView.as_view(),
        name='ajax_post_conversation_load',
    ),

    url(
        r'^inbox/$',
        InboxView.as_view(),
        name='inbox_view',
    ),

    url(
        r'^notifications/$',
        NotificationsView.as_view(),
        name='notifications_view',
    ),

    url(
        r'^ax_profile_avatar/$',
        UpdateProfileAvatarForm.as_view(),
        name='update_profile_avatar_form',
    ),

    url(
        r'^ax_email_notification_update/$',
        EmailNotificationsUpdateView.as_view(),
        name='ax_email_notification_update',
    ),

    url(
        r'^ax_add_user_to_address_book/(?P<pk>\d+)/$',
        AddUserToAddressBookView.as_view(),
        name='ajax_add_user_to_address_book',
    ),

    url(
        r'^ax_remove_user_from_address_book/(?P<pk>\d+)/$',
        RemoveUserFromAddressBookView.as_view(),
        name='ajax_remove_user_from_address_book',
    ),

    url(
        r'^ax_add_company_to_address_book/(?P<pk>\d+)/$',
        AddCompanyToAddressBookView.as_view(),
        name='ajax_add_company_to_address_book',
    ),

    url(
        r'^ax_remove_company_to_address_book/(?P<pk>\d+)/$',
        RemoveCompanyToAddressBookView.as_view(),
        name='ajax_remove_company_from_address_book',
    ),
]

app/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns

from .views import ContactFormView
from .views import LandingPageView
from .views import DashboardView
from .views import JobOfferApplyView
from .views import JobOfferDetail
from .views import JobsList
from .views import ProfessionalDetail
from .views import user_logout
from .views import CompanyDetail
from .views import CompanyList
from .views import SignupView
from account.forms import UserPasswordResetForm

admin.site.site_title = 'QueryJane'
admin.site.site_header = 'QueryJane - Administrador'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    url(
        r'^$',
        LandingPageView.as_view(),
        name='landing_page',
    ),

    url(
        r'^signup/$',
        SignupView.as_view(),
        name='signup',
    ),

    url(
        r'^dashbaord/$',
        DashboardView.as_view(),
        name='dashboard',
    ),

    url(
        r'^companies/$',
        CompanyList.as_view(),
        name='companies_list',
    ),

    url(
        r'^jobs/$',
        JobsList.as_view(),
        name='jobs_list',
    ),

    url(
        r'^jobs/(?P<slug>[-\w]+)/$',
        JobOfferDetail.as_view(),
        name='job_offer_detail',
    ),

    url(
        r'^jobs/(?P<slug>[-\w]+)/apply/$',
        JobOfferApplyView.as_view(),
        name='job_offer_apply',
    ),

    url(
        r'^contact_form/$',
        ContactFormView.as_view(),
        name='contact_form',
    ),

    url(
        r'^contact_form_success/$',
        TemplateView.as_view(template_name='corporative/contact_form_success.html'),
        name='contact_form_success',
    ),

    url(
        r'^password/recovery/$',
        auth_views.PasswordResetView.as_view(
            template_name='account/auth/password_reset_form.html',
            form_class=UserPasswordResetForm,
            html_email_template_name='account/auth/password_reset_email.html',
        ),
        name='password_reset',
    ),

    url(
        r'^password/recovery/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/auth/password_reset_done.html',
        ),
        name='password_reset_done',
    ),

    url(
        r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('auth_login'),
            post_reset_login=True,
            template_name='account/auth/password_reset_confirm.html',
            post_reset_login_backend=(
                'django.contrib.auth.backends.AllowAllUsersModelBackend'
            ),
        ),
        name='password_reset_confirm',
    ),

    url(
        r'^login/$',
        auth_views.login,
        {
            'template_name': 'account/auth/login.html',
            'redirect_authenticated_user': True,
        },
        name='auth_login',
    ),

    url(
        r'^logout/$',
        user_logout,
        name='user_logout',
    ),

    url(
        r'^corporative/',
        include(
            'corporative.urls',
            namespace='corporative',
        )
    ),
    url(r'^account/', include('account.urls', namespace='account')),

    url(
        r'^entrepreneur/',
        include(
            'entrepreneur.urls',
            namespace='entrepreneur',
        )
    ),
    url(r'^place/', include('place.urls', namespace='place')),

    url(
        r'^(?P<slug>[-\w]+)/$',
        CompanyDetail.as_view(),
        name='venture_detail',
    ),
    url(
        r'^profile/(?P<slug>[-\w]+)/$',
        ProfessionalDetail.as_view(),
        name='professional_detail',
    ),
)

corporative/urls.py
from django.conf.urls import url

from .views import ActivateJobOfferView
from .views import ActivateCompanyView
from .views import AdminDashboardView
from .views import HideJobOfferView
from .views import HideCompanyView
from .views import LegalItemView
from .views import LegalItemFormView
from .views import TwitterShareJobView
from .views import TwitterShareCompanyView
from .views import LegalItemAgreeView
from .views import CityBulkFormView

urlpatterns = [
    url(
        r'^admin_dashboard/$',
        AdminDashboardView.as_view(),
        name='admin_dashboard',
    ),

    url(
        r'^ax-twitter-share/(?P<slug>[-\w]+)/venture/$',
        TwitterShareCompanyView.as_view(),
        name='ax_twitter_share_company',
    ),

    url(
        r'^ax-twitter-share/(?P<slug>[-\w]+)/job/$',
        TwitterShareJobView.as_view(),
        name='ax_twitter_share_job',
    ),

    url(
        r'^ax-hide/(?P<slug>[-\w]+)/venture/$',
        HideCompanyView.as_view(),
        name='ax_hide_company',
    ),

    url(
        r'^ax-activate/(?P<slug>[-\w]+)/venture/$',
        ActivateCompanyView.as_view(),
        name='ax_activate_company',
    ),

    url(
        r'^ax-hide/(?P<slug>[-\w]+)/job_offer/$',
        HideJobOfferView.as_view(),
        name='ax_hide_job_offer',
    ),

    url(
        r'^ax-activate/(?P<slug>[-\w]+)/job_offer/$',
        ActivateJobOfferView.as_view(),
        name='ax_activate_job_offer',
    ),

    url(
        r'^legal_item_agree/(?P<slug>[-\w]+)/$',
        LegalItemAgreeView.as_view(),
        name='legal_item_agree',
    ),

    url(
        r'^city-bulk-form/$',
        CityBulkFormView.as_view(),
        name='city_bulk_form',
    ),

    url(
        r'^(?P<slug>[-\w]+)/update/$',
        LegalItemFormView.as_view(),
        name='legal_item_form',
    ),
    url(
        r'^(?P<slug>[-\w]+)/',
        LegalItemView.as_view(),
        name='legal_item',
    ),
]

entrepreneur/urls.py
from django.conf.urls import url

from .views.contact_venture_settings import AjaxContactVentureFormView
from .views.contact_venture_settings import AjaxLocationVentureFormView
from .views.contact_venture_settings import AjaxMediaVentureFormView
from .views.contact_venture_settings import ContactCompanyFormView
from .views.general_venture_settings import ActivateCompanyView
from .views.general_venture_settings import CompanyCategoryView
from .views.general_venture_settings import DeactivateCompanyView
from .views.general_venture_settings import DeleteCompanyView
from .views.general_venture_settings import GeneralCompanyFormView
from .views.general_venture_settings import TransferCompanyView
from .views.general_venture_settings import UpdateCompanyLogoForm
from .views.general_venture_settings import UpdateVentureDescriptionForm
from .views.general_venture_settings import DeleteCompanyMessageView
from .views.manage_job_offers import JobOfferCloseView
from .views.manage_job_offers import JobOfferFormView
from .views.manage_job_offers import JobOffersListView
from .views.manage_job_offers import JobOfferUpdateView
from .views.messages import MessagesView
from .views.privacy_venture_settings import PrivacyVentureFormView
from .views.roles_venture_settings import MembershipLineView
from .views.roles_venture_settings import RolesCompanyFormView
from .views.roles_venture_settings import DeleteMembershipView
from .views.venture_views import CompanySearch
from .views.venture_views import VentureFormView


urlpatterns = [
    url(
        r'^$',
        VentureFormView.as_view(),
        name='venture_form',
    ),
    url(
        r'^ax_company_autocomplete/$',
        CompanySearch.as_view(),
        name='ax_company_autocomplete',
    ),

    url(
        r'^general/(?P<slug>[-\w]+)/$',
        GeneralCompanyFormView.as_view(),
        name='general_venture_form',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/update_logo/$',
        UpdateCompanyLogoForm.as_view(),
        name='update_company_logo_form',
    ),

    url(
        r'^ax_update_company_category/(?P<slug>[-\w]+)/$',
        CompanyCategoryView.as_view(),
        name='ax_update_company_category',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/update_description/$',
        UpdateVentureDescriptionForm.as_view(),
        name='update_company_description_form',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/trasnfer/$',
        TransferCompanyView.as_view(),
        name='ax_transfer_company',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/deactivate/$',
        DeactivateCompanyView.as_view(),
        name='ax_deactivate_company',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/activate/$',
        ActivateCompanyView.as_view(),
        name='ax_activate_company',
    ),

    url(
        r'^(?P<slug>[-\w]+)/delete-company-message/$',
        DeleteCompanyMessageView.as_view(),
        name='delete_company_message',
    ),

    url(
        r'^(?P<slug>[-\w]+)/delete/$',
        DeleteCompanyView.as_view(),
        name='delete_company',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/contact/$',
        ContactCompanyFormView.as_view(),
        name='contact_venture_form',
    ),

    url(
        r'^ax-update-venture-contact/(?P<pk>\d+)/$',
        AjaxContactVentureFormView.as_view(),
        name='ax_contact_venture_form',
    ),

    url(
        r'^ax-update-venture-location/(?P<pk>\d+)/$',
        AjaxLocationVentureFormView.as_view(),
        name='ax_location_venture_form',
    ),

    url(
        r'^ax-update-venture-media/(?P<pk>\d+)/$',
        AjaxMediaVentureFormView.as_view(),
        name='ax_media_venture_form',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/roles/$',
        RolesCompanyFormView.as_view(),
        name='roles_venture_form',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/messages/$',
        MessagesView.as_view(),
        name='messages_adim',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/job_offers/$',
        JobOffersListView.as_view(),
        name='job_offers_list',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/job_offer_form/$',
        JobOfferFormView.as_view(),
        name='job_offer_form',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/job_offer_update/$',
        JobOfferUpdateView.as_view(),
        name='job_offer_update',
    ),

    url(
        r'^ax-settings/(?P<slug>[-\w]+)/job_offer_close/$',
        JobOfferCloseView.as_view(),
        name='job_offer_close',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/privacy/$',
        PrivacyVentureFormView.as_view(),
        name='privacy_venture_form',
    ),

    url(
        r'^get-membership-line/$',
        MembershipLineView.as_view(),
        name='membership_line_url',
    ),

    url(
        r'^ax-delete-membership/(?P<membership_id>\d+)/$',
        DeleteMembershipView.as_view(),
        name='delete_membership',
    ),
]

place/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: QJane
from django.conf.urls import url

from .views import CitySearch
from .views import CountrySearch
from .views import CityCreate
from .views import CountryFlag
from .views import GetStateOptions
from .views import GetCityOptions


urlpatterns = [
    url(
        r'^country-search/$',
        CountrySearch.as_view(),
        name='country_search',
    ),

    # API City-Serch
    url(
        r'^city-search/$',
        CitySearch.as_view(),
        name='city_search',
    ),

    url(
        r'^ax-city-create/$',
        CityCreate.as_view(),
        name='ax_city_create',
    ),

    url(
        r'^ax-country-flag/$',
        CountryFlag.as_view(),
        name='country_flag',
    ),

    url(
        r'^ax-get-state-option/$',
        GetStateOptions.as_view(),
        name='get_state_options',
    ),

    url(
        r'^ax-get-city-option/$',
        GetCityOptions.as_view(),
        name='get_city_options',
    ),
]

entrepreneur/templates/entrepreneur/company_score_line.html
{% load company_score_tags i18n %}
<tr>
    <td>
        <img style="width: 50px; height: 50px" class="media-object" src="{{ company_score.user.get_avatar }}" alt="{{ company_score.user }}">
        <p>{{ company_score.user }}</p>

        <div class="jsLineScore" data-score="{{ company_score.score }}"></div>

        {% if company_score.comment %}
        <p class="jsScoreComment" data-comment="{{ company_score.comment }}">{{ company_score.comment|linebreaks }}</p>
        {% endif %}

        <p>{{ company_score.created_at }}</p>

        {% get_can_edit_company_score user company_score.user company_score.company as can_edit_company_score %}
        {% if can_edit_company_score %}
        <a href="javascript:void(0);" class="btn btn-danger jsScoreRemove" data-company-score-remove-url="{% url 'account:company_score_remove' company_score.id %}">{% trans 'Remove' %}</a>

        <a href="javascript:void(0);" class="btn btn-info jsScoreEdit" data-company-score-edit-url="{% url 'account:company_score_edit' company_score.id %}">{% trans 'Edit' %}</a>
        {% endif %}
    </td>
</tr>

entrepreneur/templates/entrepreneur/job_detail.html
{% extends "layout/base.html" %}
{% load static entrepreneur_tags i18n %}

{% block title %}{{ job_offer }} | {{ job_offer.venture }}{% endblock %}

{% block meta_title %}{{ job_offer }} | {{ job_offer.venture }}{% endblock %}

{% block meta_description %}{{ job_offer.description|truncatechars_html:200 }}{% endblock %}

{% block meta_image %}
{% if not job_offer.venture.logo %}https://queryjane.net{% endif %}{{ job_offer.venture.get_logo }}
{% endblock %}

{% get_company_logo_extension job_offer.venture.get_logo as company_logo_extension %}
{% block meta_image_type %}{{ company_logo_extension }}{% endblock %}

{% block meta_twitter_title %}
{{ job_offer }} | {{ job_offer.venture }}
{% endblock %}

{% block meta_twitter_description %}
{{ job_offer.description|truncatechars_html:200 }}
{% endblock %}

{% block meta_twitter_image %}
{% if not job_offer.venture.logo %}https://queryjane.net{% endif %}{{ job_offer.venture.get_logo }}
{% endblock %}

{% block content %}
<div class="container">
  {% if job_offer.venture.is_inactive %}<div class="alert alert-danger" role="alert">{{ job_offer.venture }} {% trans "is inactive. Only company administrators and platform administrators can view this page." %}</div>
  {% elif job_offer.venture.is_hidden %}
  <div class="alert alert-warning" role="alert">{{ job_offer.venture }} {% trans 'has been hidden by a QueryJane administrator.' %}</div>
  {% endif %}

  <div class="row">
    <div class="col-12 col-sm-3">
      <div class="media-object">
        <div class="row">
          <div class="col-xs-8 col-sm-11 col-md-9">
            <img class="img-fluid" src="{{ job_offer.venture.get_logo }}" alt="{{ job_offer.venture }}" style="margin-bottom: 0;">
          </div>
        </div>
      </div>

      <h3><a href="{{ job_offer.venture.get_absolute_url }}">{{ job_offer.venture }}</a></h3>

      <div class="panel panel-default">
        <div class="panel-heading">
          <i class="fa fa-briefcase" aria-hidden="true"></i>

          <span>{% trans 'Job offer' %}: {% if job_offer.industry_categories.count > 1 %}{% trans 'categories' %}{% else %}{% trans 'category' %}{% endif %}</span>
        </div>

        <div class="panel-body">
          {% get_current_language as LANGUAGE_CODE %}
          <ul>
          {% for industry_category in job_offer.industry_categories.all %}
            <li>
            {% if LANGUAGE_CODE == 'es' %}
            {{ industry_category.name_es }}
            {% else %}
            {{ industry_category.name_en }}
            {% endif %}
            </li>
          {% endfor %}
          </ul>
        </div>
      </div>

      {% if job_offer.country or job_offer.city %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <i class="fa fa-location-arrow" aria-hidden="true"></i>
          <span>{% trans 'Job location' %}</span>
        </div>

        <div class="panel-body">
          {% if job_offer.country %}
          <div>
            <img src="{{ job_offer.country.flag }}">
            <span>{{ job_offer.country }}</span>
          </div>
          {% endif %}

          {% if job_offer.city %}
          <div>
            <span>{{ job_offer.city }} {% if job_offer.state %}, {{ job_offer.state }}.{% endif %}</span>
          </div>
          {% endif %}
        </div>
      </div>
      {% endif %}

      {% if permission_app.manage_admin_views %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <i class="fa fa-star" aria-hidden="true"></i>
          <span>{% trans 'Qjane Admin' %}</span>
        </div>

        <div class="panel-body">
          <div class="JSJobActions">
            {% if not job_offer.shared_on_twitter and job_offer.is_active %}
            <a href="javascript:void(0)" class="JSShareJob btn btn-ghost-purple" data-share-url="{% url 'corporative:ax_twitter_share_job' job_offer.slug %}">
                <i class="fa fa-twitter"></i><i class="fa fa-facebook"></i> {% trans 'Share' %}
            </a>
            {% endif %}

            <a href="javascript:void(0)" class="js_hideJobOffer btn btn-ghost-purple" data-hide-url="{% url 'corporative:ax_hide_job_offer' job_offer.slug %}" style="{% if job_offer.is_hidden %}display:none;{% endif %}">
                <i class="fa fa-eye-slash"></i> {% trans 'Hide' %}
            </a>

            <a href="javascript:void(0)" class="js_activateJobOffer btn btn-ghost-purple" data-activate-url="{% url 'corporative:ax_activate_job_offer' job_offer.slug %}" style="{% if not job_offer.is_hidden %}display:none;{% endif %}">
                <i class="fa fa-fire"></i> {% trans 'Activate' %}
            </a>
          </div>
        </div>
      </div>
      {% endif %}
    </div>

    <div class="col-12 col-sm-9 JOContainer">
      <h1>{{ job_offer }}</h1>

      <p><strong>Status:</strong>
      {% if job_offer.is_active %}
      <span class="JODetailStatus badge badge-success">{% trans 'Active' %}</span>
      {% elif job_offer.is_hidden %}
      <span class="JODetailStatus badge badge-warning">{% trans 'Hidden' %}</span>
      {% else %}
      <span class="JODetailStatus badge badge-warning">{% trans 'Closed' %}</span>
      {% endif %}
      </p>

      <p><strong>{% trans 'Created at:' %}</strong> {{ job_offer.created_at }}</p>
      <p><strong>{% trans 'Job type:' %}</strong> {{ job_offer.get_job_type_display }}</p>

      <div>
      {% if job_offer.description %}
        <div class="QJRedactorContent">
            {{ job_offer.description|safe }}
        </div>
      {% endif %}
      </div>

    {% if can_edit %}
      <div class="pull-right jsJobActions">
        <a href="{% url 'entrepreneur:job_offer_update' job_offer.slug %}" class="btn btn-ghost-purple">{% trans 'Edit job offer' %}</a>

        <a href="javascript:void(0)" class="btn btn-danger job_offer_close_link" data-job-offer-id="{{ job_offer.id }}" data-close-job-url="{% url 'entrepreneur:job_offer_close' job_offer.slug %}">{% trans 'Close job offer' %}</a>
      </div>
    {% endif %}

    {% if can_manage %}
      <h3>{% trans 'Applicants list' %}</h3>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'application date' %}</th>
            <th>{% trans 'Actions' %}</th>
          </tr>
        </thead>

          <tbody>
          {% for applicant in job_offer.applicant_set.all %}
              <tr>
                <td>{{ applicant.applicant }}</td>
                <td>{{ applicant.created_at }}</td>
                <td>
                  <a href="{% url 'professional_detail' applicant.applicant.slug %}">
                    {% trans 'View profile' %}
                  </a>
                </td>
              </tr>
          {% empty %}
              <tr>
                <td>{% trans 'There are not applicants yet.' %}</td>
              </tr>
          {% endfor %}
          </tbody>
      </table>

      <a href="{% url 'entrepreneur:job_offers_list' job_offer.venture.slug %}" class="btn btn-ghost-purple">{% trans 'Go to job offers administration panel' %} - {{ job_offer.venture }}</a>
    {% endif %}

      {% if can_apply %}
      <a class="btn btn-primary" href="{% url 'job_offer_apply' job_offer.slug %}">Apply</a>
      {% endif %}

      {% if has_applied %}
      <div class="alert alert-success" role="alert">
        {% trans 'You have applied to this offer.' %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'dist/js/entrepreneur/job_offer_actions.min.js' %}"></script>
<script src="{% static 'dist/js/corporative/staff_company_actions.min.js' %}"></script>
{% endblock %}