account/urls.py
from django.conf.urls import url

from account.views.address_book import AddCompanyToAddressBookView
from account.views.address_book import AddressBookView
from account.views.address_book import AddUserToAddressBookView
from account.views.address_book import RemoveCompanyToAddressBookView
from account.views.address_book import RemoveUserFromAddressBookView
from account.views.company_score import CompanyScoreEditView
from account.views.company_score import CompanyScoreFormView
from account.views.company_score import CompanyScoreRemoveView
from account.views.messages import InboxView
from account.views.messages import LoadConversationView
from account.views.messages import UserMessageFormView
from account.views.notifications import AdminNotificationAcceptView
from account.views.notifications import AdminNotificationRejectView
from account.views.notifications import AdminNotificationResendView
from account.views.notifications import LoadNotificationModal
from account.views.notifications import NotificationsView
from account.views.profile import DeactivateAccountView
from account.views.profile import DeleteAccountMessageView
from account.views.profile import DeleteAccountView
from account.views.profile import EmailNotificationsUpdateView
from account.views.profile import NewUserLandingView
from account.views.profile import ProfessionalProfileCategoryView
from account.views.profile import ProfileSearch
from account.views.profile import UpdateProfileAvatarForm
from account.views.profile import UpdateProfileDescriptionForm
from account.views.profile import UpdateProfileFormView
from account.views.profile import ActivateAccountView

urlpatterns = [
    # API Userprofile
    url(
        r'^profile-search/$',
        ProfileSearch.as_view(),
        name='profile-search',
    ),

    url(
        r'^landing/$',
        NewUserLandingView.as_view(),
        name='signup_landing',
    ),

    url(
        r'^update/$',
        UpdateProfileFormView.as_view(),
        name='profile_update',
    ),

    url(
        r'^ax-deactivate-account/$',
        DeactivateAccountView.as_view(),
        name='deactivate_account',
    ),

    url(
        r'^ax-activate-account/$',
        ActivateAccountView.as_view(),
        name='activate_account',
    ),

    url(
        r'^ax-delete-account-message/$',
        DeleteAccountMessageView.as_view(),
        name='delete_account_message',
    ),

    url(
        r'^delete/$',
        DeleteAccountView.as_view(),
        name='account_delete',
    ),

    url(
        r'^address-book/$',
        AddressBookView.as_view(),
        name='address_book',
    ),

    url(
        r'^ax_update_professional_profile_category/$',
        ProfessionalProfileCategoryView.as_view(),
        name='ax_update_professional_profile_category',
    ),

    url(
        r'^ax_account/update_description/$',
        UpdateProfileDescriptionForm.as_view(),
        name='update_profile_description_form',
    ),

    url(
        r'^ax-post-notification-load/(?P<pk>\d+)/$',
        LoadNotificationModal.as_view(),
        name='ajax_post_notification_load',
    ),

    url(
        r'^admin_notification_accept/(?P<pk>\d+)/$',
        AdminNotificationAcceptView.as_view(),
        name='admin_notification_accept',
    ),

    url(
        r'^admin_notification_reject/(?P<pk>\d+)/$',
        AdminNotificationRejectView.as_view(),
        name='admin_notification_reject',
    ),

    url(
        r'^ax_admin_notification_resend/(?P<pk>\d+)/$',
        AdminNotificationResendView.as_view(),
        name='admin_notification_resend',
    ),

    url(
        r'^ax_send_user_mesasge/$',
        UserMessageFormView.as_view(),
        name='send_user_mesasge',
    ),

    url(
        r'^ax_company_score_form/(?P<pk>\d+)/$',
        CompanyScoreFormView.as_view(),
        name='company_score_form',
    ),

    url(
        r'^ax_company_score_remove/(?P<pk>\d+)/$',
        CompanyScoreRemoveView.as_view(),
        name='company_score_remove',
    ),

    url(
        r'^ax_company_score_edit/(?P<pk>\d+)/$',
        CompanyScoreEditView.as_view(),
        name='company_score_edit',
    ),

    url(
        r'^ax-post-conversation-load/(?P<pk>\d+)/$',
        LoadConversationView.as_view(),
        name='ajax_post_conversation_load',
    ),

    url(
        r'^inbox/$',
        InboxView.as_view(),
        name='inbox_view',
    ),

    url(
        r'^notifications/$',
        NotificationsView.as_view(),
        name='notifications_view',
    ),

    url(
        r'^ax_profile_avatar/$',
        UpdateProfileAvatarForm.as_view(),
        name='update_profile_avatar_form',
    ),

    url(
        r'^ax_email_notification_update/$',
        EmailNotificationsUpdateView.as_view(),
        name='ax_email_notification_update',
    ),

    url(
        r'^ax_add_user_to_address_book/(?P<pk>\d+)/$',
        AddUserToAddressBookView.as_view(),
        name='ajax_add_user_to_address_book',
    ),

    url(
        r'^ax_remove_user_from_address_book/(?P<pk>\d+)/$',
        RemoveUserFromAddressBookView.as_view(),
        name='ajax_remove_user_from_address_book',
    ),

    url(
        r'^ax_add_company_to_address_book/(?P<pk>\d+)/$',
        AddCompanyToAddressBookView.as_view(),
        name='ajax_add_company_to_address_book',
    ),

    url(
        r'^ax_remove_company_to_address_book/(?P<pk>\d+)/$',
        RemoveCompanyToAddressBookView.as_view(),
        name='ajax_remove_company_from_address_book',
    ),
]

app/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns

from .views import ContactFormView
from .views import LandingPageView
from .views import DashboardView
from .views import JobOfferApplyView
from .views import JobOfferDetail
from .views import JobsList
from .views import ProfessionalDetail
from .views import user_logout
from .views import CompanyDetail
from .views import CompanyList
from .views import SignupView
from account.forms import UserPasswordResetForm

admin.site.site_title = 'QueryJane'
admin.site.site_header = 'QueryJane - Administrador'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    url(
        r'^$',
        LandingPageView.as_view(),
        name='landing_page',
    ),

    url(
        r'^signup/$',
        SignupView.as_view(),
        name='signup',
    ),

    url(
        r'^dashbaord/$',
        DashboardView.as_view(),
        name='dashboard',
    ),

    url(
        r'^companies/$',
        CompanyList.as_view(),
        name='companies_list',
    ),

    url(
        r'^jobs/$',
        JobsList.as_view(),
        name='jobs_list',
    ),

    url(
        r'^jobs/(?P<slug>[-\w]+)/$',
        JobOfferDetail.as_view(),
        name='job_offer_detail',
    ),

    url(
        r'^jobs/(?P<slug>[-\w]+)/apply/$',
        JobOfferApplyView.as_view(),
        name='job_offer_apply',
    ),

    url(
        r'^contact_form/$',
        ContactFormView.as_view(),
        name='contact_form',
    ),

    url(
        r'^contact_form_success/$',
        TemplateView.as_view(template_name='corporative/contact_form_success.html'),
        name='contact_form_success',
    ),

    url(
        r'^password/recovery/$',
        auth_views.PasswordResetView.as_view(
            template_name='account/auth/password_reset_form.html',
            form_class=UserPasswordResetForm,
            html_email_template_name='account/auth/password_reset_email.html',
        ),
        name='password_reset',
    ),

    url(
        r'^password/recovery/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/auth/password_reset_done.html',
        ),
        name='password_reset_done',
    ),

    url(
        r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('auth_login'),
            post_reset_login=True,
            template_name='account/auth/password_reset_confirm.html',
            post_reset_login_backend=(
                'django.contrib.auth.backends.AllowAllUsersModelBackend'
            ),
        ),
        name='password_reset_confirm',
    ),

    url(
        r'^login/$',
        auth_views.login,
        {
            'template_name': 'account/auth/login.html',
            'redirect_authenticated_user': True,
        },
        name='auth_login',
    ),

    url(
        r'^logout/$',
        user_logout,
        name='user_logout',
    ),

    url(
        r'^corporative/',
        include(
            'corporative.urls',
            namespace='corporative',
        )
    ),
    url(r'^account/', include('account.urls', namespace='account')),

    url(
        r'^entrepreneur/',
        include(
            'entrepreneur.urls',
            namespace='entrepreneur',
        )
    ),
    url(r'^place/', include('place.urls', namespace='place')),

    url(
        r'^(?P<slug>[-\w]+)/$',
        CompanyDetail.as_view(),
        name='venture_detail',
    ),
    url(
        r'^profile/(?P<slug>[-\w]+)/$',
        ProfessionalDetail.as_view(),
        name='professional_detail',
    ),
)

corporative/urls.py
from django.conf.urls import url

from .views import ActivateJobOfferView
from .views import ActivateCompanyView
from .views import AdminDashboardView
from .views import HideJobOfferView
from .views import HideCompanyView
from .views import LegalItemView
from .views import LegalItemFormView
from .views import TwitterShareJobView
from .views import TwitterShareCompanyView
from .views import LegalItemAgreeView
from .views import CityBulkFormView

urlpatterns = [
    url(
        r'^admin_dashboard/$',
        AdminDashboardView.as_view(),
        name='admin_dashboard',
    ),

    url(
        r'^ax-twitter-share/(?P<slug>[-\w]+)/venture/$',
        TwitterShareCompanyView.as_view(),
        name='ax_twitter_share_company',
    ),

    url(
        r'^ax-twitter-share/(?P<slug>[-\w]+)/job/$',
        TwitterShareJobView.as_view(),
        name='ax_twitter_share_job',
    ),

    url(
        r'^ax-hide/(?P<slug>[-\w]+)/venture/$',
        HideCompanyView.as_view(),
        name='ax_hide_company',
    ),

    url(
        r'^ax-activate/(?P<slug>[-\w]+)/venture/$',
        ActivateCompanyView.as_view(),
        name='ax_activate_company',
    ),

    url(
        r'^ax-hide/(?P<slug>[-\w]+)/job_offer/$',
        HideJobOfferView.as_view(),
        name='ax_hide_job_offer',
    ),

    url(
        r'^ax-activate/(?P<slug>[-\w]+)/job_offer/$',
        ActivateJobOfferView.as_view(),
        name='ax_activate_job_offer',
    ),

    url(
        r'^legal_item_agree/(?P<slug>[-\w]+)/$',
        LegalItemAgreeView.as_view(),
        name='legal_item_agree',
    ),

    url(
        r'^city-bulk-form/$',
        CityBulkFormView.as_view(),
        name='city_bulk_form',
    ),

    url(
        r'^(?P<slug>[-\w]+)/update/$',
        LegalItemFormView.as_view(),
        name='legal_item_form',
    ),
    url(
        r'^(?P<slug>[-\w]+)/',
        LegalItemView.as_view(),
        name='legal_item',
    ),
]

entrepreneur/urls.py
from django.conf.urls import url

from .views.contact_venture_settings import AjaxContactVentureFormView
from .views.contact_venture_settings import AjaxLocationVentureFormView
from .views.contact_venture_settings import AjaxMediaVentureFormView
from .views.contact_venture_settings import ContactCompanyFormView
from .views.general_venture_settings import ActivateCompanyView
from .views.general_venture_settings import CompanyCategoryView
from .views.general_venture_settings import DeactivateCompanyView
from .views.general_venture_settings import DeleteCompanyView
from .views.general_venture_settings import GeneralCompanyFormView
from .views.general_venture_settings import TransferCompanyView
from .views.general_venture_settings import UpdateCompanyLogoForm
from .views.general_venture_settings import UpdateVentureDescriptionForm
from .views.general_venture_settings import DeleteCompanyMessageView
from .views.manage_job_offers import JobOfferCloseView
from .views.manage_job_offers import JobOfferFormView
from .views.manage_job_offers import JobOffersListView
from .views.manage_job_offers import JobOfferUpdateView
from .views.messages import MessagesView
from .views.privacy_venture_settings import PrivacyVentureFormView
from .views.roles_venture_settings import MembershipLineView
from .views.roles_venture_settings import RolesCompanyFormView
from .views.roles_venture_settings import DeleteMembershipView
from .views.venture_views import CompanySearch
from .views.venture_views import VentureFormView


urlpatterns = [
    url(
        r'^$',
        VentureFormView.as_view(),
        name='venture_form',
    ),
    url(
        r'^ax_company_autocomplete/$',
        CompanySearch.as_view(),
        name='ax_company_autocomplete',
    ),

    url(
        r'^general/(?P<slug>[-\w]+)/$',
        GeneralCompanyFormView.as_view(),
        name='general_venture_form',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/update_logo/$',
        UpdateCompanyLogoForm.as_view(),
        name='update_company_logo_form',
    ),

    url(
        r'^ax_update_company_category/(?P<slug>[-\w]+)/$',
        CompanyCategoryView.as_view(),
        name='ax_update_company_category',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/update_description/$',
        UpdateVentureDescriptionForm.as_view(),
        name='update_company_description_form',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/trasnfer/$',
        TransferCompanyView.as_view(),
        name='ax_transfer_company',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/deactivate/$',
        DeactivateCompanyView.as_view(),
        name='ax_deactivate_company',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/activate/$',
        ActivateCompanyView.as_view(),
        name='ax_activate_company',
    ),

    url(
        r'^(?P<slug>[-\w]+)/delete-company-message/$',
        DeleteCompanyMessageView.as_view(),
        name='delete_company_message',
    ),

    url(
        r'^(?P<slug>[-\w]+)/delete/$',
        DeleteCompanyView.as_view(),
        name='delete_company',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/contact/$',
        ContactCompanyFormView.as_view(),
        name='contact_venture_form',
    ),

    url(
        r'^ax-update-venture-contact/(?P<pk>\d+)/$',
        AjaxContactVentureFormView.as_view(),
        name='ax_contact_venture_form',
    ),

    url(
        r'^ax-update-venture-location/(?P<pk>\d+)/$',
        AjaxLocationVentureFormView.as_view(),
        name='ax_location_venture_form',
    ),

    url(
        r'^ax-update-venture-media/(?P<pk>\d+)/$',
        AjaxMediaVentureFormView.as_view(),
        name='ax_media_venture_form',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/roles/$',
        RolesCompanyFormView.as_view(),
        name='roles_venture_form',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/messages/$',
        MessagesView.as_view(),
        name='messages_adim',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/job_offers/$',
        JobOffersListView.as_view(),
        name='job_offers_list',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/job_offer_form/$',
        JobOfferFormView.as_view(),
        name='job_offer_form',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/job_offer_update/$',
        JobOfferUpdateView.as_view(),
        name='job_offer_update',
    ),

    url(
        r'^ax-settings/(?P<slug>[-\w]+)/job_offer_close/$',
        JobOfferCloseView.as_view(),
        name='job_offer_close',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/privacy/$',
        PrivacyVentureFormView.as_view(),
        name='privacy_venture_form',
    ),

    url(
        r'^get-membership-line/$',
        MembershipLineView.as_view(),
        name='membership_line_url',
    ),

    url(
        r'^ax-delete-membership/(?P<membership_id>\d+)/$',
        DeleteMembershipView.as_view(),
        name='delete_membership',
    ),
]

app/templates/layout/menu/_navbar_user_menu.html
{% load entrepreneur_tags notifications messages general_forms widget_tweaks i18n %}
<ul class="nav navbar-nav navbar-right">

    {% get_user_notifications_count user as user_notifications_count %}
    {% get_new_user_notifications_count user as new_user_notifications_count %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" {% if user_notifications_count %}href="#" id="navbarDropdownNotificationsLink" data-toggle="dropdown"{% endif %} title="{% if user_notifications_count %}{% trans 'Notifications' %}{% else %}{% trans 'There are not new notifications' %}{% endif %}">

        {% if user_notifications_count %}
            <i class="fa fa-bell" aria-hidden="true"></i>
        {% else %}
            <i class="fa fa-bell-slash" aria-hidden="true"></i>
        {% endif %}

            {% if new_user_notifications_count %}(<span class="NewNotificationsCounter">{{ new_user_notifications_count }}</span>){% endif %}
        </a>

        {% get_recent_user_notifications user as recent_user_notifications %}
        <ul class="dropdown-menu header-notification-list"  aria-labelledby="navbarDropdownNotificationsLink">
        {% for notification in recent_user_notifications %}
            <li class="dropdown-item" data-toggle="modal" data-target="#generalModalMessage">
                <div class="qjane-notification-link d-block" data-notification-url="{% url 'account:ajax_post_notification_load' notification.pk  %}">
                    <div class="media">
                        <i class="JSNotificationStatus fa {% if notification.was_seen %}fa-eye{% else %}fa-eye-slash{% endif %} align-self-center mr-3" aria-hidden="true" title="{% if notification.was_seen %}Viewed notification{% else %}New notification{% endif %}"></i>
                        <div class="media-body align-self-center notification-container">
                            <a href="javascript:void(0)">
                                {{ notification }}
                            </a>
                        </div>
                    </div>
                </div>
            </li>
        {% endfor %}

        {% if user_notifications_count > 10 %}
            <li class="dropdown-item text-center"><a href="{% url 'account:notifications_view' %}">{% trans 'View all' %}</a></li>
        {% endif %}
        </ul>
    </li>

    {% get_user_messages_count user as user_messages_count %}
    {% get_new_user_messages_count user as new_user_messages_count %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" {% if user_messages_count %}href="#" id="navbarDropdownMessagesLink" data-toggle="dropdown"{% endif %} title="{% if user_messages_count %}{% trans 'Messages' %}{% else %}{% trans 'There are not new messages' %}{% endif %}">

            <i class="fa {% if new_user_messages_count %}fa-envelope{% else %}fa-inbox{% endif %}" aria-hidden="true"></i>

            {% if new_user_messages_count %}(<span class="NewMessagesCounter">{{ new_user_messages_count }}</span>){% endif %}
        </a>

        {% get_recent_user_conversations user as recent_user_conversations %}
        <ul class="dropdown-menu header-messages-list"  aria-labelledby="navbarDropdownMessagesLink">
        {% for conversation in recent_user_conversations %}
            <li class="dropdown-item">
                <div class="JSComposeMessage d-block" data-toggle="modal" data-target="#composeMessageModal" {% if conversation.participating_company %}data-company-to-id="{{ conversation.participating_company.id }}"{% else %}data-user-to-id="{{ conversation.get_last_message.user_from.id }}"{% endif %} data-to-name="{% if conversation.participating_company %}{{ conversation.participating_company }}{% else %}{{ conversation.get_last_message.user_from }}{% endif %}" data-load-conversation-url="{% url 'account:ajax_post_conversation_load' conversation.pk %}">
                    <div class="media">
                        <i class="JSMessagestatus fa {% if conversation.unread %}fa-envelope{% else %}fa-envelope-open{% endif %} align-self-center mr-3" title="{% if message.unread %}{% trans 'New conversation' %}{% else %}{% trans 'Viewed conversation' %}{% endif %}"></i>
                        <div class="media-body align-self-center">
                            <a href="javascript:void(0)">
                                {% if conversation.get_last_message.company_from %}
                                {{ conversation.get_last_message.company_from }}
                                {% else %}
                                {{ conversation.get_last_message.user_from }}
                                {% endif %}

                                <p class="mb-0">{{ conversation.get_last_message.created_at }}</p>
                            </a>
                        </div>
                    </div>
                </div>
            </li>
        {% endfor %}


        {% if user_messages_count > 10 %}
            <li class="dropdown-item text-center">
                <a href="{% url 'account:inbox_view' %}">{% trans 'View all' %}</a>
            </li>
        {% endif %}
        </ul>
    </li>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownSettingsLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.first_name }}
            <i class="fa fa-chevron-down fa-fw" aria-hidden="true"></i>
        </a>

        <ul class="dropdown-menu"  aria-labelledby="navbarDropdownSettingsLink">
            <li class="dropdown-item">
                <a href="{% url 'professional_detail' user.professionalprofile.slug %}" class="clearfix">
                    <span class="pull-left">{% trans 'Profile' %}</span>
                    <i class="fa fa-user pull-right" aria-hidden="true"></i>
                </a>
            </li>

            <li class="dropdown-item">
                <a href="{% url 'account:profile_update' %}" class="clearfix">
                    <span class="pull-left">{% trans 'Account' %}</span>
                    <i class="fa fa-cog pull-right" aria-hidden="true"></i>
                 </a>
             </li>

            <li class="dropdown-item">
                <a href="{% url 'entrepreneur:venture_form' %}" class="clearfix">
                    <span class="pull-left">{% trans 'New company' %}</span>
                    <i class="fa fa-briefcase pull-right" aria-hidden="true"></i>
                </a>
            </li>

            <li class="dropdown-item">
                <a href="{% url 'account:address_book' %}" class="clearfix">
                    <span class="pull-left">{% trans 'address book' %}</span>
                    <i class="fa fa-address-book pull-right" aria-hidden="true"></i>
                </a>
            </li>
        {% get_user_venture_memberships user as user_venture_memberships %}

        {% if user_venture_memberships %}
        <li role="separator" class="divider"></li>
        {% for membership in user_venture_memberships %}
            <li class="dropdown-item"><a href="{{ membership.venture.get_absolute_url }}">{{ membership.venture }}</a></li>
            <li role="separator" class="divider"></li>
        {% endfor %}
        {% endif %}

        {% if permission_app.manage_admin_views %}
            <li class="dropdown-item">
                <a href="{% url 'corporative:admin_dashboard' %}" class="clearfix">
                    <span class="pull-left">{% trans 'Qjane Admin' %}</span>
                    <i class="fa fa-star pull-right" aria-hidden="true"></i>
                </a>
            </li>
            <li role="separator" class="divider"></li>
        {% endif %}

            <li class="dropdown-item">
                <a href="{% url 'user_logout' %}" class="clearfix">
                    <span class="pull-left">{% trans 'Log out' %}</span>
                    <i class="fa fa-power-off pull-right" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </li>
</ul>

<!-- Modals -->
<div class="modal fade" id="generalModalMessage" tabindex="-1" role="dialog" aria-labelledby="generalModalMessage" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<div class="modal fade" id="composeMessageModal" tabindex="-1" role="dialog" aria-labelledby="composeMessageModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{% trans 'Compose Message' %}</h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <div class="tab-content">
                  <div id="newMessage" class="tab-pane fade in active">
                    <div class="alert alert-success" role="alert" style="display:none;">
                      {% trans 'Your message has been sent.' %}
                    </div>

                    {% get_message_form as message_form %}
                    <form id="id_send_message_form" method="post" data-send-message-url="{% url 'account:send_user_mesasge' %}">
                        {% csrf_token %}

                        <div class="form-group">
                            <label>
                                {% trans 'New message' %}
                                <span class="QJRequiredField">*</span>
                            </label>

                            {% render_field message_form.user_message class+="form-control" %}
                            {{ message_form.user_message.errors }}
                        </div>

                        <div style="display:none;">
                            {% render_field message_form.user_to_id %}
                            {% render_field message_form.company_to_id %}
                            {% render_field message_form.company_from_id %}
                        </div>

                        <button type="submit" class="btn btn-primary btn-block">{% trans 'Send' %}</button>
                    </form>

                    <div id="JSconversationDetail"></div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>