account/urls.py
from django.conf.urls import url

from account.views.address_book import AddCompanyToAddressBookView
from account.views.address_book import AddressBookView
from account.views.address_book import AddUserToAddressBookView
from account.views.address_book import RemoveCompanyToAddressBookView
from account.views.address_book import RemoveUserFromAddressBookView
from account.views.company_score import CompanyScoreEditView
from account.views.company_score import CompanyScoreFormView
from account.views.company_score import CompanyScoreRemoveView
from account.views.messages import InboxView
from account.views.messages import LoadConversationView
from account.views.messages import UserMessageFormView
from account.views.notifications import AdminNotificationAcceptView
from account.views.notifications import AdminNotificationRejectView
from account.views.notifications import AdminNotificationResendView
from account.views.notifications import LoadNotificationModal
from account.views.notifications import NotificationsView
from account.views.profile import DeactivateAccountView
from account.views.profile import DeleteAccountMessageView
from account.views.profile import DeleteAccountView
from account.views.profile import EmailNotificationsUpdateView
from account.views.profile import NewUserLandingView
from account.views.profile import ProfessionalProfileCategoryView
from account.views.profile import ProfileSearch
from account.views.profile import UpdateProfileAvatarForm
from account.views.profile import UpdateProfileDescriptionForm
from account.views.profile import UpdateProfileFormView
from account.views.profile import ActivateAccountView

urlpatterns = [
    # API Userprofile
    url(
        r'^profile-search/$',
        ProfileSearch.as_view(),
        name='profile-search',
    ),

    url(
        r'^landing/$',
        NewUserLandingView.as_view(),
        name='signup_landing',
    ),

    url(
        r'^update/$',
        UpdateProfileFormView.as_view(),
        name='profile_update',
    ),

    url(
        r'^ax-deactivate-account/$',
        DeactivateAccountView.as_view(),
        name='deactivate_account',
    ),

    url(
        r'^ax-activate-account/$',
        ActivateAccountView.as_view(),
        name='activate_account',
    ),

    url(
        r'^ax-delete-account-message/$',
        DeleteAccountMessageView.as_view(),
        name='delete_account_message',
    ),

    url(
        r'^delete/$',
        DeleteAccountView.as_view(),
        name='account_delete',
    ),

    url(
        r'^address-book/$',
        AddressBookView.as_view(),
        name='address_book',
    ),

    url(
        r'^ax_update_professional_profile_category/$',
        ProfessionalProfileCategoryView.as_view(),
        name='ax_update_professional_profile_category',
    ),

    url(
        r'^ax_account/update_description/$',
        UpdateProfileDescriptionForm.as_view(),
        name='update_profile_description_form',
    ),

    url(
        r'^ax-post-notification-load/(?P<pk>\d+)/$',
        LoadNotificationModal.as_view(),
        name='ajax_post_notification_load',
    ),

    url(
        r'^admin_notification_accept/(?P<pk>\d+)/$',
        AdminNotificationAcceptView.as_view(),
        name='admin_notification_accept',
    ),

    url(
        r'^admin_notification_reject/(?P<pk>\d+)/$',
        AdminNotificationRejectView.as_view(),
        name='admin_notification_reject',
    ),

    url(
        r'^ax_admin_notification_resend/(?P<pk>\d+)/$',
        AdminNotificationResendView.as_view(),
        name='admin_notification_resend',
    ),

    url(
        r'^ax_send_user_mesasge/$',
        UserMessageFormView.as_view(),
        name='send_user_mesasge',
    ),

    url(
        r'^ax_company_score_form/(?P<pk>\d+)/$',
        CompanyScoreFormView.as_view(),
        name='company_score_form',
    ),

    url(
        r'^ax_company_score_remove/(?P<pk>\d+)/$',
        CompanyScoreRemoveView.as_view(),
        name='company_score_remove',
    ),

    url(
        r'^ax_company_score_edit/(?P<pk>\d+)/$',
        CompanyScoreEditView.as_view(),
        name='company_score_edit',
    ),

    url(
        r'^ax-post-conversation-load/(?P<pk>\d+)/$',
        LoadConversationView.as_view(),
        name='ajax_post_conversation_load',
    ),

    url(
        r'^inbox/$',
        InboxView.as_view(),
        name='inbox_view',
    ),

    url(
        r'^notifications/$',
        NotificationsView.as_view(),
        name='notifications_view',
    ),

    url(
        r'^ax_profile_avatar/$',
        UpdateProfileAvatarForm.as_view(),
        name='update_profile_avatar_form',
    ),

    url(
        r'^ax_email_notification_update/$',
        EmailNotificationsUpdateView.as_view(),
        name='ax_email_notification_update',
    ),

    url(
        r'^ax_add_user_to_address_book/(?P<pk>\d+)/$',
        AddUserToAddressBookView.as_view(),
        name='ajax_add_user_to_address_book',
    ),

    url(
        r'^ax_remove_user_from_address_book/(?P<pk>\d+)/$',
        RemoveUserFromAddressBookView.as_view(),
        name='ajax_remove_user_from_address_book',
    ),

    url(
        r'^ax_add_company_to_address_book/(?P<pk>\d+)/$',
        AddCompanyToAddressBookView.as_view(),
        name='ajax_add_company_to_address_book',
    ),

    url(
        r'^ax_remove_company_to_address_book/(?P<pk>\d+)/$',
        RemoveCompanyToAddressBookView.as_view(),
        name='ajax_remove_company_from_address_book',
    ),
]

app/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns

from .views import ContactFormView
from .views import LandingPageView
from .views import DashboardView
from .views import JobOfferApplyView
from .views import JobOfferDetail
from .views import JobsList
from .views import ProfessionalDetail
from .views import user_logout
from .views import CompanyDetail
from .views import CompanyList
from .views import SignupView
from account.forms import UserPasswordResetForm

admin.site.site_title = 'QueryJane'
admin.site.site_header = 'QueryJane - Administrador'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    url(
        r'^$',
        LandingPageView.as_view(),
        name='landing_page',
    ),

    url(
        r'^signup/$',
        SignupView.as_view(),
        name='signup',
    ),

    url(
        r'^dashbaord/$',
        DashboardView.as_view(),
        name='dashboard',
    ),

    url(
        r'^companies/$',
        CompanyList.as_view(),
        name='companies_list',
    ),

    url(
        r'^jobs/$',
        JobsList.as_view(),
        name='jobs_list',
    ),

    url(
        r'^jobs/(?P<slug>[-\w]+)/$',
        JobOfferDetail.as_view(),
        name='job_offer_detail',
    ),

    url(
        r'^jobs/(?P<slug>[-\w]+)/apply/$',
        JobOfferApplyView.as_view(),
        name='job_offer_apply',
    ),

    url(
        r'^contact_form/$',
        ContactFormView.as_view(),
        name='contact_form',
    ),

    url(
        r'^contact_form_success/$',
        TemplateView.as_view(template_name='corporative/contact_form_success.html'),
        name='contact_form_success',
    ),

    url(
        r'^password/recovery/$',
        auth_views.PasswordResetView.as_view(
            template_name='account/auth/password_reset_form.html',
            form_class=UserPasswordResetForm,
            html_email_template_name='account/auth/password_reset_email.html',
        ),
        name='password_reset',
    ),

    url(
        r'^password/recovery/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/auth/password_reset_done.html',
        ),
        name='password_reset_done',
    ),

    url(
        r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('auth_login'),
            post_reset_login=True,
            template_name='account/auth/password_reset_confirm.html',
            post_reset_login_backend=(
                'django.contrib.auth.backends.AllowAllUsersModelBackend'
            ),
        ),
        name='password_reset_confirm',
    ),

    url(
        r'^login/$',
        auth_views.login,
        {
            'template_name': 'account/auth/login.html',
            'redirect_authenticated_user': True,
        },
        name='auth_login',
    ),

    url(
        r'^logout/$',
        user_logout,
        name='user_logout',
    ),

    url(
        r'^corporative/',
        include(
            'corporative.urls',
            namespace='corporative',
        )
    ),
    url(r'^account/', include('account.urls', namespace='account')),

    url(
        r'^entrepreneur/',
        include(
            'entrepreneur.urls',
            namespace='entrepreneur',
        )
    ),
    url(r'^place/', include('place.urls', namespace='place')),

    url(
        r'^(?P<slug>[-\w]+)/$',
        CompanyDetail.as_view(),
        name='venture_detail',
    ),
    url(
        r'^profile/(?P<slug>[-\w]+)/$',
        ProfessionalDetail.as_view(),
        name='professional_detail',
    ),
)

entrepreneur/urls.py
from django.conf.urls import url

from .views.contact_venture_settings import AjaxContactVentureFormView
from .views.contact_venture_settings import AjaxLocationVentureFormView
from .views.contact_venture_settings import AjaxMediaVentureFormView
from .views.contact_venture_settings import ContactCompanyFormView
from .views.general_venture_settings import ActivateCompanyView
from .views.general_venture_settings import CompanyCategoryView
from .views.general_venture_settings import DeactivateCompanyView
from .views.general_venture_settings import DeleteCompanyView
from .views.general_venture_settings import GeneralCompanyFormView
from .views.general_venture_settings import TransferCompanyView
from .views.general_venture_settings import UpdateCompanyLogoForm
from .views.general_venture_settings import UpdateVentureDescriptionForm
from .views.general_venture_settings import DeleteCompanyMessageView
from .views.manage_job_offers import JobOfferCloseView
from .views.manage_job_offers import JobOfferFormView
from .views.manage_job_offers import JobOffersListView
from .views.manage_job_offers import JobOfferUpdateView
from .views.messages import MessagesView
from .views.privacy_venture_settings import PrivacyVentureFormView
from .views.roles_venture_settings import MembershipLineView
from .views.roles_venture_settings import RolesCompanyFormView
from .views.roles_venture_settings import DeleteMembershipView
from .views.venture_views import CompanySearch
from .views.venture_views import VentureFormView


urlpatterns = [
    url(
        r'^$',
        VentureFormView.as_view(),
        name='venture_form',
    ),
    url(
        r'^ax_company_autocomplete/$',
        CompanySearch.as_view(),
        name='ax_company_autocomplete',
    ),

    url(
        r'^general/(?P<slug>[-\w]+)/$',
        GeneralCompanyFormView.as_view(),
        name='general_venture_form',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/update_logo/$',
        UpdateCompanyLogoForm.as_view(),
        name='update_company_logo_form',
    ),

    url(
        r'^ax_update_company_category/(?P<slug>[-\w]+)/$',
        CompanyCategoryView.as_view(),
        name='ax_update_company_category',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/update_description/$',
        UpdateVentureDescriptionForm.as_view(),
        name='update_company_description_form',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/trasnfer/$',
        TransferCompanyView.as_view(),
        name='ax_transfer_company',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/deactivate/$',
        DeactivateCompanyView.as_view(),
        name='ax_deactivate_company',
    ),

    url(
        r'^ax_settings/(?P<slug>[-\w]+)/activate/$',
        ActivateCompanyView.as_view(),
        name='ax_activate_company',
    ),

    url(
        r'^(?P<slug>[-\w]+)/delete-company-message/$',
        DeleteCompanyMessageView.as_view(),
        name='delete_company_message',
    ),

    url(
        r'^(?P<slug>[-\w]+)/delete/$',
        DeleteCompanyView.as_view(),
        name='delete_company',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/contact/$',
        ContactCompanyFormView.as_view(),
        name='contact_venture_form',
    ),

    url(
        r'^ax-update-venture-contact/(?P<pk>\d+)/$',
        AjaxContactVentureFormView.as_view(),
        name='ax_contact_venture_form',
    ),

    url(
        r'^ax-update-venture-location/(?P<pk>\d+)/$',
        AjaxLocationVentureFormView.as_view(),
        name='ax_location_venture_form',
    ),

    url(
        r'^ax-update-venture-media/(?P<pk>\d+)/$',
        AjaxMediaVentureFormView.as_view(),
        name='ax_media_venture_form',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/roles/$',
        RolesCompanyFormView.as_view(),
        name='roles_venture_form',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/messages/$',
        MessagesView.as_view(),
        name='messages_adim',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/job_offers/$',
        JobOffersListView.as_view(),
        name='job_offers_list',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/job_offer_form/$',
        JobOfferFormView.as_view(),
        name='job_offer_form',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/job_offer_update/$',
        JobOfferUpdateView.as_view(),
        name='job_offer_update',
    ),

    url(
        r'^ax-settings/(?P<slug>[-\w]+)/job_offer_close/$',
        JobOfferCloseView.as_view(),
        name='job_offer_close',
    ),

    url(
        r'^settings/(?P<slug>[-\w]+)/privacy/$',
        PrivacyVentureFormView.as_view(),
        name='privacy_venture_form',
    ),

    url(
        r'^get-membership-line/$',
        MembershipLineView.as_view(),
        name='membership_line_url',
    ),

    url(
        r'^ax-delete-membership/(?P<membership_id>\d+)/$',
        DeleteMembershipView.as_view(),
        name='delete_membership',
    ),
]

place/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: QJane
from django.conf.urls import url

from .views import CitySearch
from .views import CountrySearch
from .views import CityCreate
from .views import CountryFlag
from .views import GetStateOptions
from .views import GetCityOptions


urlpatterns = [
    url(
        r'^country-search/$',
        CountrySearch.as_view(),
        name='country_search',
    ),

    # API City-Serch
    url(
        r'^city-search/$',
        CitySearch.as_view(),
        name='city_search',
    ),

    url(
        r'^ax-city-create/$',
        CityCreate.as_view(),
        name='ax_city_create',
    ),

    url(
        r'^ax-country-flag/$',
        CountryFlag.as_view(),
        name='country_flag',
    ),

    url(
        r'^ax-get-state-option/$',
        GetStateOptions.as_view(),
        name='get_state_options',
    ),

    url(
        r'^ax-get-city-option/$',
        GetCityOptions.as_view(),
        name='get_city_options',
    ),
]

entrepreneur/views/messages.py
from django.views.generic import ListView
from django.shortcuts import get_object_or_404

from account.models import UserNotification
from account.data import NEW_MESSAGE_TO_COMPANY
from entrepreneur.models import Venture
from account.models import Conversation
from entrepreneur.permissions import EntrepreneurPermissions
from app.mixins import CustomUserMixin


class MessagesView(CustomUserMixin, ListView):
    model = Conversation
    template_name = 'entrepreneur/venture_settings/conversations.html'
    context_object_name = 'conversations_list'

    def test_func(self):
        return EntrepreneurPermissions.can_manage_company(
            user=self.request.user,
            company=self.get_object(),
        )

    def get_object(self):
        return get_object_or_404(Venture, slug=self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        company = self.get_object()
        # Update message notification status
        UserNotification.objects.filter(
            notification_type=NEW_MESSAGE_TO_COMPANY,
            venture_to=company,
        ).update(was_seen=True)

        context = super().get_context_data(**kwargs)
        context['company'] = company
        context['messages_active'] = True

        return context

    def get_queryset(self):
        return Conversation.objects.filter(
            participating_company=self.get_object(),
        )

entrepreneur/views/privacy_venture_settings.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404

from entrepreneur.models import Venture
from entrepreneur.permissions import EntrepreneurPermissions
from app.mixins import CustomUserMixin


class PrivacyVentureFormView(CustomUserMixin, TemplateView):
    template_name = 'entrepreneur/venture_settings/privacy_venture_form.html'

    def test_func(self):
        return EntrepreneurPermissions.can_manage_company(
            user=self.request.user,
            company=self.get_object(),
        )

    def get_object(self):
        return get_object_or_404(Venture, slug=self.kwargs.get('slug'))

    def get(self, *args, **kwargs):
        venture = self.get_object()

        return self.render_to_response(
            self.get_context_data(
                venture=venture,
                privacy_active=True,
            )
        )

entrepreneur/templates/entrepreneur/venture_settings/general_company_settings.html
{% extends "layout/base.html" %}
{% load static widget_tweaks i18n entrepreneur_tags %}

{% block title %}{{ company }} - {% trans 'Settings' %}{% endblock %}

{% block css %}
<link href="{% static 'dist/css/entrepreneur/general_company_form.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container py-4">
  <div class="alert alert-danger jsInactiveAlert" role="alert" style="{% if company.is_active %}display:none;{% endif %}">
    {% trans "This company is inactive, so users can't find it in the application. You can activate it when you want." %}

    <a href="javascript:void(0)" id="id_activate_link_scroll">{% trans "Go to activate." %}</a>
  </div>

  <div class="row">
    {% include 'entrepreneur/venture_settings/settings_menu.html' %}

    <div class="col-md-9">
        <!-- Logo and categories -->
        <div class="card rounded-0 border-0 mb-4">
          <div class="card-header bg-qj-purple rounded-0 text-white">
              <h3 class="h5 m-0 text-white">{% trans 'General information' %}</h3>
          </div>
          <div class="card-body border border-muted border-top-0">
            {% if not company.logo %}
              <div class="alert alert-warning jsUpdateCompanyLogoMessage" role="alert">{% trans 'Update the company logo to generate greater impact and brand recall.' %}</div>
            {% endif %}

            <div class="row">
              <div class="col-md-3 col-12 QjaneCompanySettingsLogoContainer">
                <img class="img-fluid" src="{{ company.get_logo }}" alt="{{ company }}">

                <form id="id_company_change_logo_form" method="post" enctype="multipart/form-data" data-company-update-logo-url="{% url 'entrepreneur:update_company_logo_form' company.slug %}" style="display:none;">
                  {% csrf_token %}
                  <div class="logo">
                      {{ company_logo_form.logo.label_tag }}
                      {% render_field company_logo_form.logo %}
                  </div>

                  <button type="submit" id="submit_company_logo_link"></button>
                </form>

                <a class="btn btn-ghost-purple btn-block mt-3" href="javascript:void(0)" id="id_company_logo_update_link">
                  <i class="fa fa-camera fa-fw" aria-hidden="true"></i>
                  {% trans 'Update' %}
                </a>
              </div>

              <div class="col-md-9 col-12">
                {% get_current_language as LANGUAGE_CODE %}

                <p>{% trans 'Industry sectors' %}</p>

                <ul class="qjane-industry-categories-list" data-update-company-category-url="{% url 'entrepreneur:ax_update_company_category' company.slug %}">
                  {% for industry_category in industry_categories %}
                  <li>
                      <a class="btn {% if industry_category in company.industry_categories.all %}btn-primary{% else %}btn-ghost-purple{% endif %}" href="javascript:void(0)" data-category-id="{{ industry_category.id }}">
                      {% if LANGUAGE_CODE == 'es' %}
                      {{ industry_category.name_es }}
                      {% else %}
                      {{ industry_category.name_en }}
                      {% endif %}
                      </a>
                  </li>
                  {% endfor %}
                </ul>

                  <p class="QjaneEmptyCategoriesBug"></p>
              </div>
            </div>
          </div>
        </div>
        <!-- End logo and categories -->

        <!-- Company description -->
        <div class="jsDescriptionCard" data-update-company-description-form="{% url 'entrepreneur:update_company_description_form' company.slug %}">

          <form id="id_company_change_description_form" method="post">
            {% csrf_token %}
            <div class="js_lan_form_container">
              <div class="card rounded-0 border-0 mb-4">
                <div class="card-header bg-qj-purple rounded-0 text-white">
                    <span class="float-left">{% trans 'English description' %}</span>

                    <a href="javascript:void(0)" class="js_edit_desc_link float-right text-white">
                      {% trans 'Edit' %} <i class="fas fa-pencil-alt js_edit_desc_link" aria-hidden="true"></i>
                    </a>
                </div>
                <div class="card-body border border-muted border-top-0">
                  <div class="QjaneUpdatedENdescCompany"></div>

                  <div class="description_field_container" style="{% if company.description_en %}display:none;{% endif %}">

                      <div id="rich_editor_description_en">
                          {{ company.description_en|safe }}
                      </div>

                      <div style="display:none;">
                          {% render_field description_form.description_en %}
                      </div>

                      <button type="submit" class="btn btn-primary mt-xs">
                          {% trans 'Save' %}
                      </button>
                  </div>

                  <div class="desc_cont company_description_en_content">
                  {% if company.description_en %}
                      {{ company.description_en|safe }}
                  {% endif %}
                  </div>
                </div>
              </div>
            </div>

            <div class="js_lan_form_container">
              <div class="card rounded-0 border-0 mb-4">
                <div class="card-header bg-qj-purple rounded-0 text-white">
                  <span class="float-left">{% trans 'Spanish description' %}</span>

                  <a href="javascript:void(0)" class="js_edit_desc_link float-right text-white">
                    {% trans 'Edit' %} <i class="fas fa-pencil-alt js_edit_desc_link" aria-hidden="true"></i>
                  </a>
                </div>
                <div class="card-body border border-muted border-top-0">
                  <div class="QjaneUpdatedSPdescCompany"></div>

                  <div class="description_field_container" style="{% if company.description_es %}display:none;{% endif %}">
                    <div id="rich_editor_description_es">
                      {{ company.description_es|safe }}
                    </div>

                    <div style="display: none;">
                      {% render_field description_form.description_es %}
                    </div>

                    <button type="submit" class="btn btn-primary mt-xs">
                      {% trans 'Save' %}
                    </button>
                  </div>

                  <div class="desc_cont company_description_es_content">
                  {% if company.description_es %}
                    {{ company.description_es|safe }}
                  {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
        <!-- End company description -->

        <div class="card rounded-0 border-0 mb-4">
          <div class="card-header bg-qj-purple rounded-0 text-white">
            {% trans "Company settings" %}
          </div>
          <div class="card-body border border-muted border-top-0">
            <div class="row">
              {% if company.owner == user.professionalprofile %}
              <div class="col-md-6 col-12">
                  <h3>{% trans "Transfer company ownership." %}</h3>
                  {% if can_transfer %}
                  {% get_transfer_company_form company as transfer_company_form %}

                  <p>{% trans "Transfer company ownership to another active administrator. You will keep your role as administrator active." %}</p>

                  <form id="id_transfer_company_ownership" data-url="{% url 'entrepreneur:ax_transfer_company' company.slug %}" method="post">
                    {% csrf_token %}

                    <div class="logo">
                        {% render_field transfer_company_form.owner %}
                    </div>

                    <button type="submit" class="btn btn-warning">Transfer</button>
                  </form>

                  {% else %}
                  <p>{% trans 'To transfer a company to another user, this user must have an active administrator membership in the company' %}. <a href="{% url 'entrepreneur:roles_venture_form' company.slug %}">{% trans 'Go to roles section.' %}</a></p>
                  {% endif %}
              </div>
              {% endif %}

              <div class="col-md-6 col-12">
                <div id="id_deactivate_container" style="{% if company.is_inactive %}display:none;{% endif %}">
                  <h3>{% trans "Deactivate company." %}</h3>
                  <p>{% trans "Users will not be able to find your company. Users whit administrator membership can activate/deactivate a company when they want." %}</p>

                  <a href="javascript:void(0)" class="btn btn-warning jsDeactivateCompany" data-deactivate-company-url="{% url 'entrepreneur:ax_deactivate_company' company.slug %}">{% trans "Deactivate" %}</a>
                </div>

                <div id="id_activate_container" style="{% if company.is_active %}display:none;{% endif %}">
                  <h3>{% trans "Activate company." %}</h3>
                  <p>{% trans "Allow users of the application to find ." %} <strong>{{ company }}</strong></p>

                  <a href="javascript:void(0)" class="btn btn-success jsActivateCompany" data-activate-company-url="{% url 'entrepreneur:ax_activate_company' company.slug %}">{% trans "Activate" %}</a>
                </div>
              </div>

              <div class="col-md-6 col-12">
                  <h3>{% trans "Delete company." %}</h3>

                {% if can_delete %}
                  <p>{% trans "Delete company profile. Created job offers and memberships will be deleted too." %}</p>
                  <a href="{% url 'entrepreneur:delete_company' company.slug %}" class="btn btn-danger">{% trans 'Delete' %}</a>
                {% else %}
                  <p>{% trans "Only the company owner can delete it." %}</p>
                  <p><strong>{{ company.owner }}</strong> {% trans "is the company owner." %}</p>

                  <button type="button" class="btn btn-secondary btn-lg" disabled>Delete</button>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'dist/js/entrepreneur/general_company_form.min.js' %}"></script>
{% endblock %}

entrepreneur/templates/entrepreneur/venture_settings/settings_menu.html
{% load i18n %}
<div class="col-md-3">
    <div class="media mb-4">
        <i class="fa fa-building fa-3x align-self-center mr-3 text-muted" aria-hidden="true"></i>
        <div class="media-body">
            <h4 class="h3 my-0">
                <a class="text-primary" href="{{ company.get_absolute_url }}">
                    {{ company }}
                </a>
            </h4>
        </div>
    </div>

    <ul class="list-group QjaneVentureSettingsMenu">
        <li class="list-group-item {% if general_active %}active{% endif %}">
            <a href="{% url 'entrepreneur:general_venture_form' company.slug %}" class="clearfix">
                <span class="float-left">{% trans 'General' %}</span>
                <i class="fa fa-cog float-right" aria-hidden="true"></i>
            </a>
        </li>

        <li class="list-group-item {% if contact_active %}active{% endif %}">
            <a href="{% url 'entrepreneur:contact_venture_form' company.slug %}" class="clearfix">
                <span class="float-left">{% trans 'Contact' %}</span>
                <i class="fa fa-phone float-right" aria-hidden="true"></i>
        </a>
        </li>

        <li class="list-group-item {% if roles_active %}active{% endif %}">
            <a href="{% url 'entrepreneur:roles_venture_form' company.slug %}" class="clearfix">
                <span class="float-left">{% trans 'Members' %}</span>
                <i class="fa fa-users float-right" aria-hidden="true"></i>
            </a>
        </li>

        <li class="list-group-item {% if messages_active %}active{% endif %}">
            <a href="{% url 'entrepreneur:messages_adim' company.slug %}" class="clearfix">
                <span class="float-left">{% trans 'Messages' %}</span>
                <i class="fa fa-envelope float-right" aria-hidden="true"></i>
            </a>
        </li>

        <li class="list-group-item {% if jobs_active %}active{% endif %}">
            <a href="{% url 'entrepreneur:job_offers_list' company.slug %}" class="clearfix">
                <span class="float-left">{% trans 'Job Offers' %}</span>
                <i class="fa fa-industry float-right" aria-hidden="true"></i>
            </a>
        </li>

        {% comment %}
        <li class="list-group-item {% if privacy_active %}active{% endif %}">
            <a href="{% url 'entrepreneur:privacy_venture_form' company.slug %}" class="clearfix">
                <span class="float-left">{% trans 'Privacy' %}</span>
                <i class="fa fa-user-secret float-right" aria-hidden="true"></i>
            </a>
        </li>
        {% endcomment %}
    </ul>
</div>